### ISSUE TITLE
[BUG] DUMP DATA not working

### ISSUE THREAD

**Issue by init5god** [cweijan/vscode-mysql#1016]
- Database type and version: v6.9.6
- 
I wanna know why when I try to dump the data it opens a terminal and installs mysql-client on the terminal using brew. This is the first time Im facing this problem

**Comment by cweijan** [comment]
The extension uses mysqldump to export data. When mysqldump does not exist, the installation will be triggered. Please perform the dump again after the installation is completed.

**Comment by alonsoeml** [comment]
Yes I did that after the installation completed. But everytime I click on "dump data" the same happens, it opens a new terminal and it tries to install again. The result is "you already have this installed" and nothing else happens
I had to downgrade the version in order to work so Im guessing its a bug in the newest version

**Comment by cweijan** [comment]
Thanks for the feedback, I released version 6.9.7 to fix it, please try if it works normally.

**Comment by alonsoeml** [comment]
I works now. Thanks
