### ISSUE TITLE
[BUG][SECURITY] Not all Passwords are masked

### ISSUE THREAD

**Issue by iocron** [cweijan/vscode-mysql#561]
### System: 

- OS: Windows 10
- Database Type: MariaDB 10.4

### Description

Not all passwords are beeing masked. For example, if you import a SQL File and the command fails, then the password is beeing outputted in clear text. E.g.: 2022-04-26 11:18:47 Command failed: mysql -h 127.0.0.1 -P 32784 -u root -pMyPasswordInClearText --default-character-set=utf8 typo3 < /var/www/some.sql

**Comment by cweijan** [comment]
hi, I have now unmarked the password because there are too many ways to get your connection password, for example:
1. Edit the connection configuration
2. Change the password box to plaintext on the connection page.

This means that the mark password no longer has any meaning, if your machine is accessed by others, then your connection password can be obtained.
