### ISSUE TITLE
[BUG] Only 100 entries show now with pagination

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#601]
- OS: macOS 12.3.1
- Database Type: MySQL

I cannot use the limit in a query because pagination is broken at all.
Also now I cannot use search - because search works only on a current page.

Pagination is suck.

**Comment by cweijan** [comment]
Hi, in order to prevent large queries from causing the view to freeze, the limit is to display a maximum of 100 pieces of data, you can modify this setting to adjust it.
![image](https://user-images.githubusercontent.com/27798227/171640388-60af5bf4-b344-4e16-b02e-1c977e712e4f.png)

Also I don't plan to implement global search, this feature is only needed in rare cases.

**Comment by mirkadev** [comment]
Oh, thank you!
