### ISSUE TITLE
Free no maintance

### ISSUE THREAD

**Issue by Vedia-JerezDaniel** [cweijan/vscode-mysql#639]
Dear Weijan Chen,

I read your magnificent extension won't be maintain for the free plan, that's sad.

But at least, I imagine we still can use the  free plan (no maintenance), or eventually it will be only for pay customers?

I really would love to pay for your work, but at office I use SQL snowflake, and I already pay Copitot.

Hope you can answer me back.

Bests

**Comment by cweijan** [comment]
Are you using ssh client? I just updated it to the latest version, the free function remains the same.

**Comment by Vedia-JerezDaniel** [comment]
Hi there, I'm sorry for the question, thanks for the answer.

I close the issue.

Keep up the good work.

**Comment by etonu** [comment]
Hi @cweijan thanks for making this great project! :smiley: 
Is the Version thats on [marketplace.visualstudio.com](https://marketplace.visualstudio.com/publishers/cweijan) or https://open-vsx.org/extension/cweijan/vscode-mysql-client2 still OpenSource?
Since there seem to be awesome new featues: https://marketplace.visualstudio.com/items/cweijan.vscode-mysql-client2/changelog which the changelog of this repo lacks. :(
In both marketplaces your extension is said to be under the MIT Open Source License.
I love software where the source code is available, because it means that people are able to look into the source code and see/verify what it does. And also contribute by making PRs & debug the code. Having the source code available, also means, I can invest time in learning how to use the program, because I can trust, that the software continues to exists and has the possibility to evolve, even if the only dev died in a car crash.

I totaly understand that you need money, maybe, if you make some money, you could release the source code under a source available license, which makes it possible that people can read the source code, debug and contribute but are forbidden to distribute compiled copies. Or use the featues that require a Premium license in a comercial context without a license.

**Comment by cweijan** [comment]
The version of openvsx is also closed source, and the mit does not prohibit commercialization. The version of this project a year ago is still open source in this repository.

Also, if you have a new question, it is recommended to open a new issue.

**Comment by Vedia-JerezDaniel** [comment]
Dear Cweijan

How are you?, I received this message and want to know how you are doing?

What are your next steps? And if you need some kind of help, let me know.

Enjoy the weekend crack!!

Best,


Daniel H.

**Comment by cweijan** [comment]
Hi, just another person commented under your issue, I replied to him, please enjoy your weekend.

**Comment by GitMensch** [comment]
I'm also confused and the README and CHANGELOG (at 3.9.8) and the last release (4.7) in this repo and the multitude of extensions published don't help that much....

Can you please clear this up? Then I'd be able to send a PR with adjusting the files.

I _guess_: ChangeLog was just not update since 3.9.8, while the repository got the full updates to 4.7, correct?

After 4.7 the extension was moved to "closed source", which is also possibly under MIT as this is no copyleft license (and even switching the license would be fine, as long as the copyright owners - which _may_ be solely the repository owner - want to do that) and renamed to "vscode-database-client2".
Under MIT people are still allowed to do with this extension as they like (commonly redistribute, possibly reverse-engineer or otherwise make derivative works that must be published under the same license).

Of course people still contributed and send PR here so this repo is now 4.7plus, correct?

Additional to the published "client2" extensions: they are all the same, just have a different name - or are "mysql" "postges" "sqlserver client" "database client" any different?
