### ISSUE TITLE
Connection Config: Fix buttons; Improve Cloud Sync Functionality/Discoverability

### ISSUE THREAD

**Issue by ppenguin** [cweijan/vscode-mysql#697]
Two topics:

1. The arrows on the `Import`/`Export` buttons are the "wrong" way, usually import is down and export is up.
2. It is entirely unclear how `Cloud Sync` works:
   - which "cloud" is used?
   - what kind of "encryption key" is expected?
   - if I "just try" something and try to upload, it tells me:
      ```
      The session is close, you need login again!
      ```

**Comment by cweijan** [comment]
Thanks your feed, my answer:
1. At first there was only export function, the down arrow meant to download the current result. Modifying it now will cause ambiguity to users.
2. For some reason, the session of database-client has expired, please log in again to enable cloud sync, go to https://database-client.com/#/, and click login in vscode after logging in.
3. The key is usually a private key file, it is optional, using the key will aes encrypt it on upload, so that only your private key can decrypt it.
