### ISSUE TITLE
Version 6.2.6

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#795]
Dear Sir,

From version 6.2.6, I am facing the following issue:

While updating MySQL functions and procedures, the focus moves to the first line of the document.  For example, I am in the 500th line in the procedure and if I update the procedure, the procedure gets saved in the database but the focus go to the first line of the document.  So again, I have to find and scroll down to the position where I am previously there.  Till version 6.2.5, after updating the procedure there will be no such positional change in the document.

One more request - While connecting a database using Change Active Connection option, a line showing the active connection is inserted as the first line in the document (Ex: -- Active: 1669972866873@@192.168.1.247@3306@developmentteam).  This creates problem especially while sycing procedures and function to GIT.  This will mark as a change in GIT, even though no other change
exists.  Hence request you to provide an option in settings to disable adding this line.

Request your kind attention

Thank you

**Comment by franklinkf** [comment]
One more issue, I think may be due to this version is that after selecting a whole function/procedure and updating it in the database, the selected portion remains selected/shaded.  To remove this selection/shade, I need to make a change in the document.  I am not sure, whether this a issue of this version or due to some other VS Code updates

**Comment by franklinkf** [comment]
Hats off to the other improvements 👍

**Comment by cweijan** [comment]
Thank you for your feedback, for your reply to your question
1. The focus is because the editor loses the focus when the view is opened, but it seems to have an unexpected effect.

2. I can add an option to control it, but note that disabling it will cause the association between the file and the connection to become invalid after you switch to the Query file or restart VSCode.
![image](https://user-images.githubusercontent.com/27798227/226084810-47f21b72-4bcf-4cd4-b9bd-d4d83c092c0c.png)


3. The extension will now highlight the SQL executed from the editor, but I think that for manual selection, it really doesn't need to be highlighted.

I will adjust and release a new version as soon as possible.

**Comment by franklinkf** [comment]
Thanks a lot

**Comment by franklinkf** [comment]
Closing the issue

**Comment by cweijan** [comment]
Hi, please try the latest version 6.2.8. If you have any questions, feedback is welcome.
![image](https://user-images.githubusercontent.com/27798227/226092357-1386c0dd-f143-41a8-b9a2-5b8d407fe751.png)

**Comment by franklinkf** [comment]
Great. Thank You
