### ISSUE TITLE
Stop Query

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#805]
Is there any option to stop a long running MySQL query executed using the extension?

**Comment by cweijan** [comment]
Yes, you can click this to stop query, please restore your toolbar display.

![image](https://user-images.githubusercontent.com/27798227/227691709-65442657-7b85-4c90-89e9-a0b81fff2525.png)

**Comment by cweijan** [comment]
And I'm considering removing the option to hide the toolbar, because I think the toolbar is necessary to show, this option was created for you before, please try to see if it's still necessary.
![image](https://user-images.githubusercontent.com/27798227/227692798-a9d04ef3-d5c4-43de-a367-939597dbed19.png)

**Comment by franklinkf** [comment]
Yes.  Suggestion is made from my end only.  I think it will not matter much if the option to hide the toolbar is removed.

Thanks

**Comment by cweijan** [comment]
Thanks, I will hide this option in future versions.

**Comment by franklinkf** [comment]
Now it has useful options compared to the options, when I requested to hide the toolbar.

Thanks
