### ISSUE TITLE
Connect to account server fail!

### ISSUE THREAD

**Issue by williamwallace79** [cweijan/vscode-mysql#937]
Hello community

I am trying to login via my vs-code web extension where vs-code for web is installed via a docker container on my home server.

docker is running on Debian which is install inside parallels on osx/arm.

I noticed that when I access the extension via http directly, the extension wont load.
when I access vs-code via my dns provider via https it opens and I can reach the login form.

but in any case I am not able to login and I get "Connect to account server fail!."

when I logon via the official extensions web page, it lets me in.

I am not able to use the extension without login via the vs code web interface.

the offline registration is ok. but it seems to be valid for a few weeks and than it tells me that it is not registered any longer.
I payed in august this year...

kind regards.

**Comment by cweijan** [comment]
HTTP cannot load the web view, so the extension cannot be used normally. This is a restriction imposed by VS Code for security reasons.

Failure to log in means that your docker container cannot connect to the Internet. Please consider allowing the network to work properly.

The account information has expired. I think this is because you are using code-server, and the data will be lost after it is restarted (I think this is a code-server bug). You can reactivate it with the offline license I sent before.
